---
# tasks file for ipv6

- name: Désactivation de l'ipv6
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    sysctl_file: /etc/sysctl.conf
    state: present
    reload: yes
  with_items:
    - { name: "net.ipv4.ip_forward", value: 1 }
    - { name: "net.ipv6.conf.all.disable_ipv6", value: 1 }
    - { name: "net.ipv6.conf.default.disable_ipv6", value: 1 }
    - { name: "net.ipv6.conf.default.autoconf", value: 0 }
    - { name: "net.ipv6.conf.all.autoconf", value: 0 }

...